name: "Check PR content"
on:
  pull_request:
    types: [opened, edited, review_requested, ready_for_review]

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
    - name: Check PR
      uses: JJ/github-pr-contains-action@releases/v14.1
      with:
        github-token: ${{github.token}}
        # Only use Numpy to initialize NaT values!
        # See #674 and #727 for more discussion
        diffDoesNotContain: 'pd.NaT'
